### ISSUE TITLE
 SVGElement is not defined

### ISSUE THREAD

**Issue by FluffierThanThou** [svgdotjs/svgdom#1]
Just stumbled upon this project, and it looks like a good solution for serving svg's.

However, when attempting to use the basic example, I immediately run into the below issue. I haven't used SVG.js before, so I'm not really sure where to even begin debugging this.

```js
ReferenceError: SVGElement is not defined
    at /www/server/node_modules/svg.js/dist/svg.js:278:68
    at Object.filter (/www/server/node_modules/svg.js/dist/svg.js:261:11)
    at Object.filterSVGElements (/www/server/node_modules/svg.js/dist/svg.js:278:17)
    at create.children (/www/server/node_modules/svg.js/dist/svg.js:3088:38)
    at create.each (/www/server/node_modules/svg.js/dist/svg.js:3129:27)
    at create.writeDataToDom (/www/server/node_modules/svg.js/dist/svg.js:1259:12)
    at create.svg (/www/server/node_modules/svg.js/dist/svg.js:1242:14)
    at /www/server/routes/svg.js:16:20
    at Layer.handle [as handle_request] (/www/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/www/server/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/www/server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/www/server/node_modules/express/lib/router/layer.js:95:5)
    at /www/server/node_modules/express/lib/router/index.js:277:22
    at param (/www/server/node_modules/express/lib/router/index.js:349:14)
    at param (/www/server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/www/server/node_modules/express/lib/router/index.js:410:3)
```

The relevant route;
```js
const express = require('express');
const router = express.Router();

const window   = require('svgdom')
const SVG      = require('svg.js')(window)
const document = window.document

router.get( "*", function( req, res, next ){
    // create svg.js instance
    const draw = SVG(document.documentElement)

    // use svg.js as normal
    draw.rect(100,100).fill('yellow').move(50,50)

    // get your svg as string
    // res.setHeader( "Content-Type", "image/svg+xml");
    res.send(draw.svg());
});

module.exports = router;
```

`draw.node.outerHtml` is likewise undefined...

**Comment by Fuzzyma** [comment]
@FluffierThanThou thanks for checking this out. You need to use the `current master` of svg.js to use svgdom. We did not make a push with the recent changes (which are basically prefix all global variables with window). Sorry for the inconvenience. We will try to release that soon.

**Comment by FluffierThanThou** [comment]
ah, no worries. Thanks for the quick reply! 

(may want to add that to the description for now though)

**Comment by FluffierThanThou** [comment]
did `npm install git+https://github.com/svgdotjs/svg.js.git`, which has done the trick. 

Thanks for this, I wasn't looking forward to making my stack even more complicated with PhantomJS involved.

**Comment by Fuzzyma** [comment]
Its mentioned now in the docs that the minimum version required is 2.5.1 :)
