### ISSUE TITLE
 ReferenceError: ij is not defined

### ISSUE THREAD

**Issue by kimmobrunfeldt** [svgdotjs/svgdom#10]
When dx is set for tspan element, calling SVG.js method rbox() causes an error. 

```
ReferenceError: ij is not defined
    at textIterator (/home/kimmo/svgdom/utils/bboxUtils.js:143:35)
    at bbox (/home/kimmo/svgdom/utils/bboxUtils.js:97:19)
    at create.getBoundingClientRect (/home/kimmo/svgdom/class/Node.js:290:14)
    at new create (/home/kimmo/myproject/node_modules/svg.js/dist/svg.js:2341:39)
    at create.rbox (/home/kimmo/myproject/node_modules/svg.js/dist/svg.js:2364:14)
    at _getBBoxForSvgElement (/home/kimmo/myproject/dist/core/get-bbox.js:297:29)
```  

This happens because of the for loop breaking expression `j < ij`: https://github.com/svgdotjs/svgdom/blob/42819a810b87a59dfecf0bd5cd0c317dc586f3b2/utils/bboxUtils.js#L143. 

I suspect it's just a typo and should actually read `j < jl`.

**Comment by Fuzzyma** [comment]
I guess you are right :D
