### ISSUE TITLE
'fontkit' does not provide an export named 'openSync'

### ISSUE THREAD

**Issue by fhirter** [svgdotjs/svgdom#115]
i am using svgdom to run tests using jest.

Until svgdom version 0.1.14 the following code was working.

```javascript
import crypto from "crypto";
import {createSVGWindow} from "svgdom";
import {registerWindow} from "@svgdotjs/svg.js";
import {expect, test} from "@jest/globals";

// register window and document
const window = createSVGWindow()
const document = window.document
registerWindow(window, document)
```
 In version 0.1.17. it fails with:
```
    SyntaxError: The requested module 'fontkit' does not provide an export named 'openSync'

      at Runtime.linkAndEvaluateModule (node_modules/jest-runtime/build/index.js:708:5)
```

**Comment by fhirter** [comment]
> Running your code gives no output. Can you add more context so it shows the error?

updated the issue. Its run by jest test runner.

**Comment by Fuzzyma** [comment]
no, that doesnt really help. I pushed a possible fix. Please try the current master version and report if it works

**Comment by fhirter** [comment]
> no, that doesnt really help. I pushed a possible fix. Please try the current master version and report if it works

I did your changes manually and the error was resolved.

But another error appears:
```
    ReferenceError: TextDecoder is not defined

      at node_modules/fontkit/dist/src/utils.js:28:29
```

**Comment by Fuzzyma** [comment]
This seems to be on fontkits side now. jest doesnt work great with esm modules. You might want to read trough https://jestjs.io/docs/ecmascript-modules

**Comment by mattsputnikdigital** [comment]
Im getting this building a React app in Vite

No matching export in "node_modules/fontkit/dist/browser-module.mjs" for import "openSync"

    node_modules/svgdom/src/config.js:2:9:
      2 │ import { openSync } from 'fontkit'

**Comment by Fuzzyma** [comment]
@mattsputnikdigital did you try current master? Please report back if it works

**Comment by mattsputnikdigital** [comment]
@Fuzzyma yes the master branch fixes the problem so you are good to include that fix in a new release.

**Comment by Fuzzyma** [comment]
nice. thanks for letting me know

**Comment by Fuzzyma** [comment]
released as 0.1.18
