### ISSUE TITLE
Using SVG.invent with SVG.js v3

### ISSUE THREAD

**Issue by mike-arlington** [svgdotjs/svgdom#45]
I wonder if there is a way to use svg.js ability to define custom shapes with svgdom. I am using svgdom@0.0.20 and @svgdotjs/svg.js@3.0.13. The following code works fine in the browser (from the docs):

```javascript
...
SVG.Rounded = SVG.invent({
    // Define the type of element that should be created
    create: 'rect',

    // Specify from which existing class this shape inherits
    inherit: SVG.Shape,

    // Add custom methods to invented shape
    extend: {
        // Create method to proportionally scale the rounded corners
        size: function (width, height) {
            return this.attr({
                width: width
                , height: height
                , rx: height / 5
                , ry: height / 5
            })
        }
    },

    // Add method to parent elements
    construct: {
        // Create a rounded element
        rounded: function (width, height) {
            return this.put(new SVG.Rounded).size(width, height)
        }
    }
});
```

It fails under nodejs, however, at the line ```SVG.Rounded = SVG.invent({``` with the following stack trace:

```
/home/mike/node_modules/@svgdotjs/svg.js/dist/svg.node.js:2407
    this.type = node.nodeName;
                     ^
TypeError: Cannot read property 'nodeName' of undefined
    at new Dom (/home/mike/node_modules/@svgdotjs/svg.js/dist/svg.node.js:2407:22)
    at new Element (/home/mike/node_modules/@svgdotjs/svg.js/dist/svg.node.js:2688:5)
    at new Shape (/home/mike/node_modules/@svgdotjs/svg.js/dist/svg.node.js:3106:1)
    at Function.invent (/home/mike/node_modules/@svgdotjs/svg.js/dist/svg.node.js:308:29)
    at Object.<anonymous> (/home/mike/dev/projects/svg-test/test.js:16:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

SVG.extend appears to works fine with nodejs with the following code:
```javascript
'use strict';

const window = require('svgdom');
const document = window.document;

const obj = require('@svgdotjs/svg.js');
obj.registerWindow(window, document);

const SVG = (arg) => {
    return obj.SVG(arg);
};

Object.assign(SVG, obj);
const canvas = SVG(document.documentElement);

// this works
SVG.extend(SVG.Element, {
...
}

// this fails
SVG.Rounded = SVG.invent({
...
}

```

**Comment by Fuzzyma** [comment]
Invent was actually removed in favor of es6 classes in version 3. However, we reimplemented it because of all those plugins using it. However, seems like the implementation is buggy so we might remove it as well.

To achieve what you want you can use:

```js
class Rounded extends SVG.Rect {
  constructor (node) {
    super(nodeOrNew('rect', node), node)
  }

  size: function (width, height) {
      return this.attr({
          width: width
          , height: height
          , rx: height / 5
          , ry: height / 5
      })
  }
}

SVG.extend(SVG.Container {
  rounded () {
    return this.put(new Rounded).size(width, height)
  }
}

```

That should do the trick. If not you can look into the src for many examples

**Comment by mike-arlington** [comment]
Thank you for your response. It's still not working but I'll try to dig into source to see if I can make it work.
