### ISSUE TITLE
DocumentFragment: if detached, assigning textContent crashes

### ISSUE THREAD

**Issue by michael-brade** [svgdotjs/svgdom#65]
This here doesn't work anymore:
```
var f = document.createDocumentFragment();
f.textContent = "";
```
I don't know if the spec allows it but it works in the browser.
The reason in svgdom is that `this.ownerDocument` is null, but it is used for the `createTextNode()` call. It is actually true for any detached Node since this code is in `dom/Node.js`, line 399.

**Comment by michael-brade** [comment]
Actually, it is allowed :) In the browser, `f.ownerDocument` is not null, it is `document`. So `createDocumentFragment()` has to set the `ownerDocument`.

**Comment by Fuzzyma** [comment]
Well if only documentFragment is missing its ownerDocument its an easy fix. Guess I forgot to set it on creation. Already fixed in my code now - thanks! :)

**Comment by michael-brade** [comment]
Hm. It doesn't work. I am not completely sure but I think `DocumentFragment`'s CTOR doesn't forward `props` to `Node`'s CTOR.

Here are my changes to `main-require.cjs`, `Node` CTOR (around line 1212):
```
    this.childNodes = []                                                                                              
                                                                                                                                                                                              
    this.attrs = props.attrs || new Set()
                                                                                                                      
console.log("CTOR: ", props.ownerDocument);                                                                             
console.log("CTOR: props:", props)                                                                                      
    this.ownerDocument = props.ownerDocument || null
console.log("CTOR owner: ", this.ownerDocument);                                                                        
console.trace()                                                                                                         
    this.parentNode = null                                                                                                                      
```


And here is the output:
```
create fragment
CTOR:  undefined
CTOR: props: {}
CTOR owner:  null
Trace
    at new Node (LaTeX.js/node_modules/svgdom/main-require.cjs:1219:9)
    at new DocumentFragment (LaTeX.js/node_modules/svgdom/main-require.cjs:713:5)
    at Document.createDocumentFragment (LaTeX.js/node_modules/svgdom/main-require.cjs:645:13)
    at HtmlGenerator.exports.HtmlGenerator.HtmlGenerator.parseMath (LaTeX.js/dist/latex.js:40628:19)
    at peg$c285 (LaTeX.js/dist/latex.js:1114:44)
    at peg$parseinline_math (LaTeX.js/dist/latex.js:9128:19)
```

**Comment by Fuzzyma** [comment]
Guess I was a bit lazy there. Sorry. I pushed and released a fix

**Comment by michael-brade** [comment]
Awesome! Works now :grin:
