### ISSUE TITLE
bbox() for text: TypeError: Cannot read property 'fontFamilyMappings' of null

### ISSUE THREAD

**Issue by kimmobrunfeldt** [svgdotjs/svgdom#7]
Hi!

You have done incredible effort to make SVG.js work in Node, thank you. I'm trying to calculate bounding box for a text element in an existing SVG file. I'm using node 6.9.4, svg.js@2.6.2 and latest master of svgdom. Here's a reproducible example:

```js
const window = require('svgdom');
const svgJs = require('svg.js');

const SVG_STRING = `
<svg width="100px" height="100px" viewBox="0 0 100 100" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <text id="text" font-family="Arial" font-size="16" font-weight="300" letter-spacing="16.363636" fill="#343434">
    <tspan x="10" y="10">Test</tspan>
  </text>
</svg>`;


const SVG = svgJs(window);
const draw = SVG(window.document);
draw.svg(SVG_STRING);

const element = SVG.get('text');
console.log(element.bbox());
```

Running this causes an error: 

```
/Users/kimmo/myproject/node_modules/svgdom/class/Node.js:416
        fontFamilyMappings: this.ownerDocument.fontFamilyMappings,
                                              ^

TypeError: Cannot read property 'fontFamilyMappings' of null
    at create.getFontDetails (/Users/kimmo/myproject/node_modules/svgdom/class/Node.js:416:47)
    at textIterator (/Users/kimmo/myproject/node_modules/svgdom/utils/bboxUtils.js:154:68)
    at bbox (/Users/kimmo/myproject/node_modules/svgdom/utils/bboxUtils.js:97:19)
    at create.getBBox (/Users/kimmo/myproject/node_modules/svgdom/class/Node.js:287:14)
    at new create (/Users/kimmo/myproject/node_modules/svg.js/dist/svg.js:2292:28)
    at create.bbox (/Users/kimmo/myproject/node_modules/svg.js/dist/svg.js:2319:14)
    at Object.<anonymous> (/Users/kimmo/myproject/test2.js:17:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

I'm not sure if this is problem of SVG.js or svgdom, but ownerDocument is not set for the text element. Here you can find where .parentNode is set for the element, maybe we should have ownerDocument there as well: https://github.com/svgdotjs/svgdom/blob/a34be21e61000b067ce1b00242d43a6684234b5d/class/Node.js#L182

**Comment by Fuzzyma** [comment]
the ownerDocument is set in the `document.createElement` method and therefore any node created by svgdom should have it set. I wonder why it is not set in your case.
Well - actually I wonder no more. I just saw that when importing svg, the constructors are used directly and not via `createElement` and thats why it isnt working. Will try to fix it soon.
Thank you for reporting!
